kind: pipeline
name: default

workspace:
  base: /book
  path: PanBook

steps:
- name: build
  image: docker:18.09-git
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - export TAG=`git describe --tags --exact-match 2> /dev/null || echo "latest"`
  - docker build -t ann17/panbook:$TAG .
  - docker tag ann17/panbook:$TAG panbook:latest

- name: doc-epub
  image: ann17/panbook:latest
  pull: always
  commands:
  - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- src); then exit 78; fi
  - DEBUG="-d" make epub
  depends_on:
  - build

- name: doc-ctexbook
  image: ann17/panbook:latest
  pull: always
  commands:
  - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- src); then exit 78; fi
  - DEBUG="-d" make ctex
  - grep -iE "warning|at lines" build/*-ctexbook-pc.log
  depends_on:
  - build

- name: doc-ctexbook-6inch
  image: ann17/panbook:latest
  pull: always
  commands:
  - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- src); then exit 78; fi
  - DEBUG="-d" make ctex6in
  - grep -iE "warning|at lines" build/*-ctexbook-mobile.log
  depends_on:
  - build
  - doc-ctexbook

- name: doc-elegantbook
  image: ann17/panbook:latest
  pull: always
  commands:
  - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- src); then exit 78; fi
  - DEBUG="-d" make elegantbook
  - grep -iE "warning|at lines" build/*-elegantbook-pc.log
  depends_on:
  - build
  - doc-ctexbook-6inch

- name: demo-article
  image: ann17/panbook:latest
  pull: always
  commands:
  - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- demo/article); then exit 78; fi
  - cd demo/article
  - DEBUG=-d make build
  - grep -iE "warning|at lines" build/*.log
  depends_on:
  - build
  
- name: demo-slide
  image: ann17/panbook:latest
  pull: always
  commands:
  - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- demo/beamer); then exit 78; fi
  - cd demo/beamer
  - make all-theme
  depends_on:
  - build
  - demo-article

- name: demo-cv
  image: ann17/panbook:latest
  pull: always
  commands:
  - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- demo/cv); then exit 78; fi
  - cd demo/cv
  - make all
  - grep -iE "warning|at lines" build/*.log
  depends_on:
  - build
  - demo-slide

- name: demo-thesis
  image: ann17/panbook:latest
  pull: always
  commands:
  - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- demo/thesis); then exit 78; fi
  - cd demo/thesis
  - make all
  - grep -iE "warning|at lines" build/*.log
  depends_on:
  - build
  - demo-slide

- name: publish-epub
  image: annprog/rsync:latest
  pull: always
  settings:
    src: build/*.epub
    dest: 172.17.0.1::panbook
  depends_on:
  - doc-epub

- name: publish-doc
  image: annprog/rsync:latest
  pull: always
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - doc-ctexbook
  - doc-ctexbook-6inch
  - doc-elegantbook

- name: publish-article
  image: annprog/rsync:latest
  pull: always
  settings:
    src: demo/article/build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - demo-article

- name: publish-slide
  image: annprog/rsync:latest
  pull: always
  settings:
    src: demo/beamer/build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - demo-slide  

- name: publish-cv
  image: annprog/rsync:latest
  pull: always
  settings:
    src: demo/cv/build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - demo-cv 

- name: publish-thesis
  image: annprog/rsync:latest
  pull: always
  settings:
    src: demo/thesis/build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - demo-thesis

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock  