#!/bin/bash
[ "$TRACE"x == "x"x ] && set -x

SCRIPTDIR=`cd $(dirname $0);pwd`
cwd=`pwd`
ofile=`echo $cwd |awk -F '/' '{print $NF}'`

source $SCRIPTDIR/libs/helper.sh
source $SCRIPTDIR/libs/env.sh

getEnv SRC "src"
WORKDIR="$cwd/$SRC"
getEnv IMGDIR "$WORKDIR/images"

BUILD="$cwd/build"
METADATA="$WORKDIR/metadata.yaml"

source $SCRIPTDIR/libs/core.sh

info "Welcome to PanBook!"
note "ScriptDir: $SCRIPTDIR"
note "WorkDir: $WORKDIR"
note "ImgDir: $IMGDIR"

# 引入模块
for module in `ls $SCRIPTDIR/libs/module-*`;do
	item=`basename $module`
	source $SCRIPTDIR/libs/$item
done


if [ $# -ge 1 ];then
	[ "$1"x == "help"x ] && printhelp
	func=$1
	shift
else
	printhelp
fi

# pandoc 通过 -V 传递给模板的变量
PANDOCVARS=""

for i in "$@"
do
	key=$1
	case $key in
	-h|--help)
		FUNCHELP=true
		shift;;
	--tpl=*)
		TPL=${key#*=}
		shift;;
	--theme=*)
		THEME=${key#*=}
		shift;;
	-d|--debug)
		DEBUG=true
		shift;;
	-V)
		PANDOCVARS="$PANDOCVARS -V $2"
		shift 2;;
	*);;
	esac
done

if [ "`type -t $func`"x == "function"x ];then
	$func
else
	error "Function: $func  not defined"
fi
